apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tce-repository
  namespace: pkg-gitops
  annotations:
    kapp.k14s.io/change-group: "tce-repo"
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tce/main:0.10.0
